int32 range # zeroPointOneMeter(1), oneMeter(10)} (0..10000)
int32 horizontal_opening_angle_start # zeroPointOneDegree(1), oneDegree(10), unavailable(3601)} (0..3601)
int32 horizontal_ppening_angle_end # zeroPointOneDegree(1), oneDegree(10), unavailable(3601)} (0..3601)

bool has_vertical_opening_angle_start
int32 vertical_opening_angle_start # zeroPointOneDegree(1), oneDegree(10), unavailable(3601)} (0..3601)
bool has_vertical_opening_angle_end
int32 vertical_opening_angle_end # zeroPointOneDegree(1), oneDegree(10), unavailable(3601)} (0..3601)
