name: Build Debian Package
on:
  workflow_dispatch:
  push:
    branches: [ "humble" ]
  pull_request:
    branches: [ "humble" ]
permissions:
  contents: read
jobs:
  build_debian:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependecies
      run: |  
        sudo apt-get update
        sudo apt-get install -y python3-bloom python3-rosdep2 fakeroot debhelper dh-python
    - name: Checkout repository
      if: always()
      uses: actions/checkout@v4
      with:
        ref: humble
        path: etsi_its_msgs
    - name: Build debian package
      run: |
        cd etsi_its_msgs
        rosdep update
        bloom-generate rosdebian --os-name ubuntu --os-version jammy --ros-distro humble
        fakeroot debian/rules binary
