name: Build Debian Package
on:
  push:
    branches: [ "humble" ]
  pull_request:
    branches: [ "humble" ]
permissions:
  contents: read
jobs:
  build_debian:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependecies
      run: |  
        sudo apt-get update
        sudo apt-get install -y python3-bloom python3-rosdep2 fakeroot debhelper dh-python
    - name: Initialize rosdep
      run: |  
       rosdep update
    - name: Checkout repository
      if: always()
      uses: actions/checkout@v4
      with:
        ref: humble
        path: etsi_its_msgs
    - name: Build debian package
      run: |
        pwd
        ls -lah
        cd etsi_its_msgs
        bloom-generate rosdebian
        fakeroot debian/rules binary
        pwd
        ls -lah
